### ISSUE TITLE
Documents do not leave the job progress queue

### ISSUE THREAD

**Issue by faddyjeros** [relativitydev/wikitivity#8]
The application is requesting the documents from wikipedia and is populating the job progress as expected. However, the document tab never gets populated and the agent just runs in a neverending loop.

Any ideas?

**Comment by dudemail** [comment]
@faddyjeros I had the same issue but have managed to resolve it. You need to go check the event logs on the agent server hosting the wikitivity upload agent for errors. Mine was to do with the fact that the keplerservicespi was set to localhost, once I updated this to point to a webserver, the issue was resolved. However now the agent completes, but no documents are uploaded.

Does anyone know why the agent cycles through all the requestIDs and completes, but never uploads any items to the documents object? Any help would be appreciated.

**Comment by faddyjeros** [comment]
@dudemail Thank you very much for this response.
I was able to play around with my agent server and updated the value of the APi. 

The documents do go through into the document object within my workspace now. I am not certain as to how it does not for you. The only change I did was the one you mention in the first paragraph of your response.

**Comment by Strijdhagen** [comment]
I'm having similar issues and am getting the following error on the agent server. The web API config looks to be fine though.
Any idea what it might be?
I'm using 10.3 btw

Agent failed in execution: kCura.WinEDDS.Exceptions.InvalidLoginException: Login failed. ---> System.Exception: Unknown failure during authentication ---> System.Net.WebException: The request failed with HTTP status 404: Not Found.
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at kCura.EDDS.WebAPI.UserManagerBase.UserManager.ClearCookiesBeforeLogin()
   at kCura.WinEDDS.Service.UserManager.LoginInternal(String emailAddress, String password)
   at kCura.WinEDDS.Service.UserManager._Closure$__2-0._Lambda$__0()
   at kCura.WinEDDS.Service.WebServiceExtensions.RetryOnReLoginException[T](SoapHttpClientProtocol input, Func`1 serviceCall, Boolean retryOnFailure)
   at kCura.WinEDDS.Service.UserManager.Login(String emailAddress, String password)
   at kCura.WinEDDS.Api.LoginHelper.LoginUsernamePassword(String username, String password, CookieContainer cookieContainer, String webServiceUrl, CancellationToken token, ILog logger)
   at ImportCredentialManager.GetCredentials(String UserName, String Password)
   --- End of inner exception stack trace ---
   at ImportCredentialManager.GetCredentials(String UserName, String Password)
   at kCura.Relativity.ImportAPI.ImportAPI.PerformLogin(String userName, String password, String webServiceURL)
   --- End of inner exception stack trace ---
   at kCura.Relativity.ImportAPI.ImportAPI.PerformLogin(String userName, String password, String webServiceURL)
   at kCura.Relativity.ImportAPI.ImportAPI..ctor(String userName, String password, String webServiceUrl)
   at kCura.Relativity.ImportAPI.ImportAPI.CreateByBearerToken(String webServiceUrl, String bearerToken)
   at kCura.Relativity.ImportAPI.ImportAPI.CreateByRsaBearerToken(String webServiceUrl)
   at Wikitivity.Agent.WikitivityAgentHelper.ImportDocument(IAgentHelper helper, Int32 workspaceID, List`1 batchedArticleList, AgentBase aB)
   at Wikitivity.Agent.WikitivityUploadsAgent.Execute() : kCura.WinEDDS.Exceptions.InvalidLoginException: Login failed. ---> System.Exception: Unknown failure during authentication ---> System.Net.WebException: The request failed with HTTP status 404: Not Found.
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at kCura.EDDS.WebAPI.UserManagerBase.UserManager.ClearCookiesBeforeLogin()
   at kCura.WinEDDS.Service.UserManager.LoginInternal(String emailAddress, String password)
   at kCura.WinEDDS.Service.UserManager._Closure$__2-0._Lambda$__0()
   at kCura.WinEDDS.Service.WebServiceExtensions.RetryOnReLoginException[T](SoapHttpClientProtocol input, Func`1 serviceCall, Boolean retryOnFailure)
   at kCura.WinEDDS.Service.UserManager.Login(String emailAddress, String password)
   at kCura.WinEDDS.Api.LoginHelper.LoginUsernamePassword(String username, String password, CookieContainer cookieContainer, String webServiceUrl, CancellationToken token, ILog logger)
   at ImportCredentialManager.GetCredentials(String UserName, String Password)
   --- End of inner exception stack trace ---
   at ImportCredentialManager.GetCredentials(String UserName, String Password)
   at kCura.Relativity.ImportAPI.ImportAPI.PerformLogin(String userName, String password, String webServiceURL)
   --- End of inner exception stack trace ---
   at kCura.Relativity.ImportAPI.ImportAPI.PerformLogin(String userName, String password, String webServiceURL)
   at kCura.Relativity.ImportAPI.ImportAPI..ctor(String userName, String password, String webServiceUrl)
   at kCura.Relativity.ImportAPI.ImportAPI.CreateByBearerToken(String webServiceUrl, String bearerToken)
   at kCura.Relativity.ImportAPI.ImportAPI.CreateByRsaBearerToken(String webServiceUrl)
   at Wikitivity.Agent.WikitivityAgentHelper.ImportDocument(IAgentHelper helper, Int32 workspaceID, List`1 batchedArticleList, AgentBase aB)
   at Wikitivity.Agent.WikitivityUploadsAgent.Execute()
